

let paymentMode='annual';
let tariffsUnlocked=false;
// Interface lock only: a static page cannot enforce private access.
const TARIFF_PIN='1234';
function requestTariffs(event){if(tariffsUnlocked)return;event.preventDefault();$('tariffPin').value='';clearTariffPinError();showDialog('tariffPinModal');setTimeout(()=>$('tariffPin').focus(),60)}
function guardTariffPanel(){if(!tariffsUnlocked&&$('tariffPanel').open)$('tariffPanel').open=false}
function clearTariffPinError(){$('tariffPinError').textContent='';$('tariffPin').removeAttribute('aria-invalid')}
function unlockTariffs(){if($('tariffPin').value!==TARIFF_PIN){$('tariffPinError').textContent='Неверный PIN-код. Попробуйте ещё раз.';$('tariffPin').setAttribute('aria-invalid','true');$('tariffPin').focus();$('tariffPin').select();return}tariffsUnlocked=true;$('tariffControls').disabled=false;$('tariffAccess').textContent='Открыто';hideDialog('tariffPinModal');$('tariffPin').value='';$('tariffPanel').open=true}
let products={online:false,musoft:false,milk:false};
let farms=[newFarm('Ферма 1')];
function newFarm(name){return {id:Date.now()+Math.random(),name,herd:'',milkData:true,milking:true,feeding:true,extras:[]}}
const $=id=>document.getElementById(id);
const val=id=>{const n=Number($(id)?.value||0);return Number.isFinite(n)?Math.max(0,n):0};
const count=id=>Math.min(100000,Math.floor(val(id)));
const money=n=>{const nearest=Math.round(n);return Math.abs(n-nearest)<=Number.EPSILON*Math.max(1,Math.abs(n))*4?nearest:Math.ceil(n)};
const fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(money(Number(n)||0))+' ₽';
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function cardToggle(e,key){if(e.target.closest('.switch'))return;const input=$('product-'+key);input.checked=!input.checked;setProduct(key,input.checked)}
function setProduct(key,on){products[key]=!!on;$('product-'+key).checked=!!on;$('card-'+key).classList.toggle('active',!!on);$('aiSection').classList.toggle('hidden',!products.online);updateSelection();renderFarms();recalc()}
function updateSelection(){const names=[];if(products.online)names.push('Онлайн‑ферма');if(products.musoft)names.push('Мусофт');if(products.milk)names.push('Учёт молока');$('selectionLabel').textContent=names.length?names.join(' + '):'Ничего не выбрано';const any=names.length>0;$('noProducts').classList.toggle('hidden',any);$('farms').classList.toggle('hidden',!any)}
function setPayment(mode){paymentMode=mode;$('payment-annual').checked=mode==='annual';$('payment-monthly').checked=mode==='monthly';$('payAnnual').classList.toggle('active',mode==='annual');$('payMonthly').classList.toggle('active',mode==='monthly');renderFarmPricesOnly();recalc()}
function openDiscountModal(){const current=Math.max(0,Math.min(50,Number($('managerDiscount').value)||0));$('discountDraft').value=current;showDialog('discountModal');setTimeout(()=>$('discountDraft').focus(),60)}
function closeDiscountModal(){hideDialog('discountModal')}
function discountBackdrop(e){if(e.target.id==='discountModal')closeDiscountModal()}
function syncDiscount(v){v=Math.max(0,Math.min(50,Number(v)||0));$('managerDiscount').value=v;$('discountLaunchChip').textContent=v+'%';$('discountLaunchChip').classList.toggle('active',v>0);$('discountLaunchText').textContent=v>0?('Скидка '+v+'%'):'Не задана';recalc()}
function setDiscount(v){syncDiscount(v)}
function applyDiscount(){if(!$('discountDraft').checkValidity()||$('discountDraft').value===''){toast('Введите целую скидку от 0 до 50%');$('discountDraft').focus();return}const raw=Number($('discountDraft').value);const v=Math.max(0,Math.min(50,Number.isFinite(raw)?raw:0));$('discountDraft').value=v;syncDiscount(v);closeDiscountModal();toast(v>0?('Скидка '+v+'% применена'):'Скидка не применяется')}
function clearDiscount(){syncDiscount(0);$('discountDraft').value=0;closeDiscountModal();toast('Скидка сброшена')}
function settingsChanged(){renderFarms();recalc()}
function step(id,d){const el=$(id);el.value=Math.max(0,(Number(el.value)||0)+d);recalc()}
function addFarm(){farms.push(newFarm('Ферма '+(farms.length+1)));renderFarms();recalc();setTimeout(()=>document.querySelector('.farm-card:last-child')?.scrollIntoView({behavior:'smooth',block:'center'}),40)}
function removeFarm(i){if(farms.length===1){toast('Нужна хотя бы одна площадка');return}farms.splice(i,1);renderFarms();recalc()}
function updateFarm(i,key,value){if(key==='herd')farms[i][key]=Math.min(10000000,Math.floor(Math.max(0,Number(value)||0)));else farms[i][key]=value;recalc()}
function toggleFarm(i,key,on,input){farms[i][key]=!!on;const system=input?.closest('.system');if(system)system.classList.toggle('active',!!on);recalc()}
function addExtra(i){const input=$('extra-'+i);const v=input.value.trim().slice(0,200);if(!v)return;if(farms[i].extras.some(x=>x.toLocaleLowerCase()===v.toLocaleLowerCase())){toast('Эта система уже добавлена');return}farms[i].extras.push(v);input.value='';renderFarms();recalc()}
function removeExtra(i,j){farms[i].extras.splice(j,1);renderFarms();recalc()}
function tariffParams(){return {base:val('sBase'),milking:val('sMilking'),feed:val('sFeed'),extra:val('sExtra'),ai:val('sAI'),markup:Math.min(1000,val('sMarkup'))/100,standaloneMarkup:Math.min(1000,val('sStandaloneMarkup'))/100,tierMin:[0,1,2,3,4,5].map(i=>Math.floor(val('tierMin'+i))),musoft:[0,1,2,3,4,5].map(i=>val('mu'+i)),milk:[0,1,2,3,4,5].map(i=>val('mi'+i)),musoftRate:[0,1,2,3,4,5].map(i=>val('muRate'+i)),milkRate:[0,1,2,3,4,5].map(i=>val('miRate'+i))}}
function tierIndex(h){h=Number(h)||0;if(h<=0)return -1;if(h<=100)return 0;if(h<=500)return 1;if(h<=1000)return 2;if(h<=1500)return 3;if(h<=2000)return 4;return 5}
function tierLabel(h){return ['50–100','100–500','500–1000','1000–1500','1500–2000','> 2000'][tierIndex(h)]||'укажите поголовье'}
function onlineBase(f,p=tariffParams()){if(!products.online)return 0;return p.base+(f.milking?p.milking:0)+(f.feeding?p.feed:0)+(f.extras.length*p.extra)}
function standaloneList(f,product,p=tariffParams()){if(!products[product])return 0;const i=tierIndex(f.herd);if(i<0)return 0;return (p[product][i]||0)+Math.max(0,Number(f.herd)-p.tierMin[i])*(p[product+'Rate'][i]||0)}
function standaloneFormula(f,product,p=tariffParams()){const i=tierIndex(f.herd);if(i<0)return 'Укажите дойное поголовье';const excess=Math.max(0,Number(f.herd)-p.tierMin[i]);const number=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n);const base=number(p[product][i]),rate=number(p[product+'Rate'][i]);const formula=base+' + '+number(excess)+' × '+rate;return paymentMode==='monthly'?'('+formula+') × '+number(1+p.standaloneMarkup):formula}
function modeFactorOnline(p){return paymentMode==='monthly'?(1+p.markup):1}
function modeFactorStandalone(p){return paymentMode==='monthly'?(1+p.standaloneMarkup):1}
function farmParts(f,p=tariffParams()){const online=money(onlineBase(f,p)*modeFactorOnline(p));const musoft=money(standaloneList(f,'musoft',p)*modeFactorStandalone(p));const milk=money(standaloneList(f,'milk',p)*modeFactorStandalone(p));return {online,musoft,milk,total:online+musoft+milk}}
function farmMonthly(f){return farmParts(f).total}
function productNames(){const a=[];if(products.online)a.push('Онлайн‑ферма');if(products.musoft)a.push('Мусофт');if(products.milk)a.push('Учёт молока');return a}
function renderFarms(){$('aiParking').append?.($('aiSection'));const any=productNames().length>0;$('noProducts').classList.toggle('hidden',any);$('farms').classList.toggle('hidden',!any);if(!any){$('farms').innerHTML='';return}const p=tariffParams();$('farms').innerHTML=farms.map((f,i)=>{const parts=farmParts(f,p);const herdNeeded=products.musoft||products.milk;const onlineBlock=products.online?`<div class="subblock fade-in"><div class="subblock-title"><strong>Системы Онлайн‑фермы</strong><span>Переключите то, что подключаем</span></div><div class="systems">
<div class="system active"><div class="system-copy"><strong>Система управления стадом</strong><span>Входит в базовый тариф</span><div class="system-price free">включено</div></div><label class="switch disabled"><input type="checkbox" checked disabled><span class="switch-track"></span></label></div>
<div class="system ${f.milkData?'active':''}"><div class="system-copy"><strong>Система учёта молока</strong><span>Можно не использовать — базовая цена не меняется</span><div class="system-price free">в базе</div></div><label class="switch"><input type="checkbox" ${f.milkData?'checked':''} onchange="toggleFarm(${i},'milkData',this.checked,this)"><span class="switch-track"></span></label></div>
<div class="system ${f.milking?'active':''}"><div class="system-copy"><strong>Доильный зал</strong><span>Подключение данных доильного оборудования</span><div class="system-price">+ ${fmt(p.milking)}/мес.</div></div><label class="switch"><input type="checkbox" ${f.milking?'checked':''} onchange="toggleFarm(${i},'milking',this.checked,this)"><span class="switch-track"></span></label></div>
<div class="system ${f.feeding?'active':''}"><div class="system-copy"><strong>Управление кормлением</strong><span>Подключение системы кормления</span><div class="system-price">+ ${fmt(p.feed)}/мес.</div></div><label class="switch"><input type="checkbox" ${f.feeding?'checked':''} onchange="toggleFarm(${i},'feeding',this.checked,this)"><span class="switch-track"></span></label></div>
</div><div class="online-addons ${i===0?'':'single'}">${i===0?'<div class="ai-slot"></div>':''}<div class="option-card extra-wrap ${f.extras.length?'active':''}"><div class="subblock-title"><strong>Дополнительные системы</strong><span>${fmt(p.extra)} / подключение</span></div><div class="extra-line"><input aria-label="Дополнительная система ${i+1}" maxlength="200" id="extra-${i}" placeholder="Например: 1С, датчики охоты, климат" onkeydown="if(event.key==='Enter'){event.preventDefault();addExtra(${i})}"><button class="btn small" onclick="addExtra(${i})">Добавить</button></div>${f.extras.length?`<div class="chips">${f.extras.map((x,j)=>`<span class="chip">${esc(x)}<button aria-label="Удалить систему ${esc(x)}" onclick="removeExtra(${i},${j})">×</button></span>`).join('')}</div>`:''}</div></div></div>`:'';
const standaloneBlock=herdNeeded?`<div class="subblock fade-in"><div class="subblock-title"><strong>Тариф по поголовью</strong><span id="farmTier-${i}">${f.herd?`Категория ${tierLabel(f.herd)}`:'Укажите поголовье'}</span></div><div class="price-breakdown">${products.musoft?`<div class="mini-price"><span>Мусофт</span><strong id="farmMu-${i}">${f.herd?fmt(parts.musoft)+'/мес.':'—'}</strong><small id="farmMuFormula-${i}">${standaloneFormula(f,'musoft',p)}</small></div>`:''}${products.milk?`<div class="mini-price"><span>Учёт молока</span><strong id="farmMi-${i}">${f.herd?fmt(parts.milk)+'/мес.':'—'}</strong><small id="farmMiFormula-${i}">${standaloneFormula(f,'milk',p)}</small></div>`:''}<div class="mini-price"><span>Категория</span><strong id="farmCat-${i}">${tierLabel(f.herd)}</strong></div></div></div>`:'';
return `<article class="farm-card fade-in"><div class="farm-head"><div class="farm-index">${i+1}</div><div class="farm-title"><strong>${esc(f.name||('Ферма '+(i+1)))}</strong><span>${productNames().join(' · ')}</span></div><div class="farm-price"><strong>${fmt(parts.total)}</strong><span>в месяц по выбранным условиям</span></div>${farms.length>1?`<button class="btn small ghost" onclick="removeFarm(${i})">Удалить</button>`:''}</div><div class="farm-body"><div class="farm-basics ${herdNeeded?'':'single'}"><div class="field"><label>Название площадки</label><input aria-label="Название площадки ${i+1}" maxlength="200" value="${esc(f.name)}" oninput="updateFarm(${i},'name',this.value)"><div class="field-spacer" aria-hidden="true"></div></div>${herdNeeded?`<div class="field"><label>Дойное поголовье</label><input id="herd-${i}" aria-label="Поголовье ${i+1}" type="number" min="1" step="1" max="10000000" placeholder="Например, 850" value="${f.herd||''}" oninput="updateFarm(${i},'herd',this.value)"><div class="hint">Число дойных животных для тарифа</div></div>`:''}</div>${onlineBlock}${standaloneBlock}</div></article>`}).join('');document.querySelector('.ai-slot')?.append($('aiSection'));labelFarmControls()}
function totals(){const p=tariffParams();let online=0,musoft=0,milk=0;farms.forEach(f=>{const x=farmParts(f,p);online+=x.online;musoft+=x.musoft;milk+=x.milk});const aiUsers=products.online?count('aiUsers'):0;const aiBase=aiUsers*p.ai;const ai=money(aiBase*modeFactorOnline(p));const gross=money(online+musoft+milk+ai);const discPct=Math.max(0,Math.min(50,val('managerDiscount')))/100;const net=money(gross*(1-discPct));const discount=gross-net;return {p,online,musoft,milk,ai,aiUsers,gross,discPct,discount,net,period:paymentMode==='annual'?money(net*12):net}}
function recalc(){const t=totals();$('aiSection').classList.toggle('active',products.online&&t.aiUsers>0);$('aiUnitPrice').textContent=fmt(money(t.p.ai*modeFactorOnline(t.p)))+'/мес. за пользователя';updatePaymentLabels(t.p);const any=productNames().length>0;
$('summaryMode').textContent=paymentMode==='annual'?'Предоплата за год':'Помесячная оплата';
if(paymentMode==='annual'){
  $('mainMoneyLabel').textContent='Платёж за 12 месяцев';
  updateTotalDisplay(t.period);
  $('mainMoneySub').innerHTML=any?`<strong>${fmt(t.net)}</strong> / мес. в пересчёте`:'выберите продукты для расчёта';
  $('invoiceLabel').textContent='В пересчёте на месяц';
  $('invoiceTotal').textContent=fmt(t.net)+'/мес.';
}else{
  $('mainMoneyLabel').textContent='Ежемесячный платёж';
  updateTotalDisplay(t.net);
  $('mainMoneySub').textContent=any?'оплата каждый месяц':'выберите продукты для расчёта';
  $('invoiceLabel').textContent='Платёж за текущий месяц';
  $('invoiceTotal').textContent=fmt(t.net);
}
$('lineOnline').classList.toggle('hidden',!products.online);$('lineMusoft').classList.toggle('hidden',!products.musoft);$('lineMilk').classList.toggle('hidden',!products.milk);$('lineAI').classList.toggle('hidden',!(products.online&&t.aiUsers>0));$('lineDiscount').classList.toggle('hidden',!(t.discPct>0));
$('onlineTotal').textContent=fmt(t.online)+'/мес.';$('musoftTotal').textContent=fmt(t.musoft)+'/мес.';$('milkTotal').textContent=fmt(t.milk)+'/мес.';$('aiTotal').textContent=fmt(t.ai)+'/мес.';$('discountTotal').textContent='−'+fmt(t.discount)+'/мес.';$('farmCount').textContent=farms.length;
const saving=$('saving');const missing=(products.musoft||products.milk)&&farms.some(f=>!Number(f.herd));if(missing){saving.classList.add('show');saving.innerHTML='Для точного расчёта Мусофт / Учёта молока укажите поголовье на каждой площадке.'}else if(t.discPct>0){saving.classList.add('show');saving.innerHTML=`Индивидуальная скидка <b>${Math.round(t.discPct*100)}%</b> уменьшает стоимость на <b>${fmt(t.discount)}</b> в месяц.`}else{saving.classList.remove('show');saving.innerHTML=''}renderFarmPricesOnly()}
function updateTotalDisplay(value){const el=$('monthlyPrice'),next=fmt(value);if(el.textContent===next)return;el.textContent=next;if(el.animate&&!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){el.getAnimations?.().forEach(animation=>animation.cancel());el.animate([{color:'#0a73f5'},{color:'#10233f'}],{duration:300,easing:'ease-out'})}}
function renderFarmPricesOnly(){document.querySelectorAll('.farm-card').forEach((card,i)=>{const f=farms[i];if(!f)return;const parts=farmParts(f);updateFarmSystemPrices(card);const title=card.querySelector('.farm-title strong');if(title)title.textContent=f.name||('Ферма '+(i+1));const el=card.querySelector('.farm-price strong');if(el)el.textContent=fmt(parts.total);const mu=$('farmMu-'+i),mi=$('farmMi-'+i),cat=$('farmCat-'+i),tier=$('farmTier-'+i);if(mu)mu.textContent=f.herd?fmt(parts.musoft)+'/мес.':'—';if(mi)mi.textContent=f.herd?fmt(parts.milk)+'/мес.':'—';const muFormula=$('farmMuFormula-'+i),miFormula=$('farmMiFormula-'+i);if(muFormula)muFormula.textContent=standaloneFormula(f,'musoft');if(miFormula)miFormula.textContent=standaloneFormula(f,'milk');if(cat)cat.textContent=tierLabel(f.herd);if(tier)tier.textContent=f.herd?'Категория '+tierLabel(f.herd):'Укажите поголовье'})}
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),2200)}
function resetAll(){products={online:false,musoft:false,milk:false};['online','musoft','milk'].forEach(k=>{$('product-'+k).checked=false;$('card-'+k).classList.remove('active')});$('aiUsers').value=0;farms=[newFarm('Ферма 1')];setDiscount(0);setPayment('annual');updateSelection();$('aiSection').classList.add('hidden');renderFarms();recalc();window.scrollTo({top:0,behavior:'smooth'});toast('Новый расчёт создан')}

function labelFarmControls(){document.querySelectorAll('.system').forEach(system=>{const input=system.querySelector('input');if(input)input.setAttribute('aria-label',system.querySelector('strong').textContent)});document.querySelectorAll('.stepper').forEach(row=>{const name=row.querySelector('input').getAttribute('aria-label');row.querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-label',(i?'Увеличить: ':'Уменьшить: ')+name))})}
function updateFarmSystemPrices(card){const p=tariffParams(),factor=modeFactorOnline(p);card.querySelectorAll('.system').forEach(system=>{const name=system.querySelector('strong')?.textContent;const price=system.querySelector('.system-price');if(!price)return;if(name==='Доильный зал')price.textContent='+ '+fmt(money(p.milking*factor))+'/мес.';if(name==='Управление кормлением')price.textContent='+ '+fmt(money(p.feed*factor))+'/мес.'});const extras=card.querySelector('.extra-wrap .subblock-title span');if(extras)extras.textContent=fmt(money(p.extra*factor))+'/мес. за систему'}
function farmSystems(f){return ['Система управления стадом',f.milkData?'Система учёта молока':null,f.milking?'Доильный зал':null,f.feeding?'Система управления кормлением':null,...f.extras].filter(Boolean)}
function updatePaymentLabels(p){$('payMonthly').querySelector('[data-payment-description]').textContent=`Онлайн-ферма и ИИ +${p.markup*100}% · Мусофт и Учёт молока +${Math.round(p.standaloneMarkup*100)}%`;$('payAnnual').querySelector('[data-payment-description]').textContent=`Платёж за 12 месяцев · базовые тарифы`}
const dialogTriggers=new Map();
function showDialog(id){dialogTriggers.set(id,document.activeElement);const modal=$(id);document.querySelectorAll('.modal.show').forEach(other=>other.inert=true);modal.inert=false;modal.classList.add('show');document.body.style.overflow='hidden';document.querySelector('.shell').inert=true;modal.focus()}
function hideDialog(id){const modal=$(id);if(!modal.classList.contains('show'))return;modal.classList.remove('show');const active=[...document.querySelectorAll('.modal.show')].at(-1);if(active)active.inert=false;const stillOpen=!!active;document.body.style.overflow=stillOpen?'hidden':'';document.querySelector('.shell').inert=stillOpen;dialogTriggers.get(id)?.focus()}
document.addEventListener('keydown',e=>{const modal=[...document.querySelectorAll('.modal.show')].at(-1);if(!modal||e.key!=='Tab')return;const nodes=[...modal.querySelectorAll('button,input,a,textarea')].filter(el=>!el.disabled&&el.offsetParent!==null);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===modal)){e.preventDefault();first?.focus()}});

document.addEventListener('keydown',e=>{if(e.key==='Escape'){const active=[...document.querySelectorAll('.modal.show')].at(-1);if(active)hideDialog(active.id)}if(e.key==='Enter'&&$('discountModal').classList.contains('show')&&document.activeElement===$('discountDraft')){e.preventDefault();applyDiscount()}});
updateSelection();renderFarms();syncDiscount(0);recalc();
