'use strict';
const deliveryState = { busy: false, sharedFile: null };
function proposalFilename(){return 'КП_Агроинтеллект_'+client().name.replace(/[\\/:*?"<>|\x00-\x1F]/g,'_').slice(0,80)+'.pdf'}
function proposalDocument(){
  const c=client(),t=totals();
  const table=(headers,body,widths)=>({table:{headerRows:1,dontBreakRows:true,widths,body:[headers.map(text=>({text,bold:true,fillColor:'#edf5fc',color:'#34536f'})),...body]},layout:'lightHorizontalLines',margin:[0,6,0,12]});
  const rows=[];
  for(const [key,label] of [['online','Онлайн-ферма'],['musoft','Мусофт'],['milk','Учёт молока']])if(products[key])rows.push([label,farms.length+' '+plural(farms.length,'площадка','площадки','площадок'),fmt(t[key])+'/мес.']);
  if(t.aiUsers)rows.push(['ИИ-помощник',t.aiUsers+' '+plural(t.aiUsers,'пользователь','пользователя','пользователей'),fmt(t.ai)+'/мес.']);
  if(t.discPct)rows.push(['Индивидуальная скидка',Math.round(t.discPct*100)+'%','−'+fmt(t.discount)+'/мес.']);
  const farmRows=farms.map((f,i)=>[(i+1)+'. '+f.name,(products.musoft||products.milk?'Поголовье: '+f.herd+'\n':'')+(products.online?farmSystems(f).join(', '):productNames().join(', ')),fmt(farmParts(f).total)+'/мес.']);
  const included=[];
  if(products.online)included.push('Онлайн-ферма: облачное хранение и обработка данных, контроль синхронизации, техническое сопровождение, стандартные отчёты, графики и уведомления. Обычные пользователи: '+count('regularUsers')+' — без доплаты.');
  if(products.musoft)included.push('Мусофт: управление стадом, карточки животных, события, рабочие задания, лечение, вакцинация, воспроизводство и отчётность.');
  if(products.milk)included.push('Учёт молока: надои, движение молока, товарность, остатки, показатели качества и аналитика реализации.');
  return {pageSize:'A4',pageMargins:[40,42,40,48],info:{title:'Коммерческое предложение для '+c.name,author:'Агроинтеллект'},defaultStyle:{font:'Roboto',fontSize:10,lineHeight:1.15,color:'#233e58'},styles:{title:{fontSize:23,bold:true,color:'#102f52',margin:[0,16,0,10]},heading:{fontSize:13,bold:true,margin:[0,12,0,4]},total:{fontSize:21,bold:true,color:'#0a63bd',margin:[0,8,0,6]}},footer:(page,pages)=>({text:'Агроинтеллект · Коммерческое предложение     '+page+' / '+pages,alignment:'right',fontSize:8,color:'#5b6f82',margin:[40,12,40,0]}),content:[
    {columns:[{stack:[{text:'АГРОИНТЕЛЛЕКТ',bold:true,fontSize:17,color:'#126ac2'},{text:'Цифровые решения для молочного животноводства',fontSize:9,margin:[0,5,0,0]}]},{stack:[{text:dateRu(),alignment:'right'},...(c.manager?[{text:'Менеджер: '+c.manager,alignment:'right',margin:[0,4,0,0]}]:[])]}]},
    {text:'Предложение для '+c.name,style:'title'},
    {text:'Предлагаем '+productNames().map(n=>'«'+n+'»').join(', ')+'. Ниже — состав решения, стоимость и выбранные условия оплаты.',margin:[0,0,0,12]},
    {text:'Стоимость',style:'heading'},table(['Позиция','Расчёт','Стоимость'],rows,['*',110,115]),
    {text:'Состав по площадкам',style:'heading'},table(['Площадка','Состав решения','Стоимость'],farmRows,[105,'*',105]),
    {text:'Что входит в предложение',style:'heading'},{ul:included,margin:[0,6,0,12]},
    {unbreakable:true,stack:[{text:'Условия оплаты',style:'heading'},{text:paymentMode==='annual'?'Предоплата за 12 месяцев.':'Помесячная оплата.'},...(t.discPct?[{text:'Индивидуальная скидка: '+Math.round(t.discPct*100)+'%.'}]:[]),{text:(paymentMode==='annual'?'Платёж за 12 месяцев: ':'Ежемесячный платёж: ')+fmt(t.period),style:'total'},...(paymentMode==='annual'?[{text:'В пересчёте на месяц: '+fmt(t.net)+'/мес.'}]:[])]},
    {text:'ООО «Агроинтеллект»',bold:true,margin:[0,14,0,4]},...(c.contact?[{text:'Контакт со стороны клиента: '+c.contact}]:[]),...(c.email?[{text:c.email}]:[])
  ]};
}
function makePdfBlob(){return new Promise((resolve,reject)=>{try{if(!window.pdfMake)throw new Error('PDF-библиотека не загрузилась');pdfMake.createPdf(proposalDocument()).getBlob(resolve)}catch(e){reject(e)}})}
function saveBlob(blob,name){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
async function downloadProposal(){if(!validateProposal()||deliveryState.busy)return;deliveryState.busy=true;try{const blob=await makePdfBlob();saveBlob(blob,proposalFilename());toast('PDF сохранён. Его можно отправить позже.')}catch(e){toast('Не удалось создать PDF. Используйте печать в PDF.')}finally{deliveryState.busy=false}}
function printProposal(){if(!validateProposal())return;renderProposal();document.body.classList.add('printing-proposal');window.print()}
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-proposal'));
window.addEventListener('beforeprint',()=>{if($('proposalModal').classList.contains('show'))document.body.classList.add('printing-proposal')});
function insertDeliveryDialogs(){
  const node=document.createElement('div');node.innerHTML=`
  <div class="modal" id="shareModal" role="dialog" aria-modal="true" aria-label="Отправить файл КП" tabindex="-1"><div class="delivery-card"><h2>Отправить КП</h2><p>На телефоне меню «Поделиться» позволяет выбрать доступный мессенджер. На компьютере сохраните PDF и прикрепите его в чате.</p><button class="btn primary" id="nativeShareButton" onclick="nativeShareProposal()">Выбрать приложение</button><button class="btn" onclick="downloadProposal()">Сохранить PDF на компьютер</button><p class="hint" id="shareHint"></p><button class="btn" onclick="hideDialog('shareModal')">Закрыть</button></div></div>
  <div class="modal" id="sendModal" role="dialog" aria-modal="true" aria-label="Отправить письмо через Kerio" tabindex="-1"><form class="delivery-card" id="sendForm"><h2>Отправка через Kerio Connect</h2><p id="sendInfo"></p><div id="kerioFields"><div class="field"><label for="senderEmail">Ваша рабочая почта</label><input id="senderEmail" type="email" autocomplete="username" required maxlength="200"></div><div class="field"><label for="senderPassword">Пароль почты</label><input id="senderPassword" type="password" autocomplete="current-password" required maxlength="500"></div><p class="hint">Пароль используется для этой отправки и не сохраняется калькулятором.</p><div class="send-review" id="sendReview"></div><button class="btn primary" id="sendButton" type="submit">Отправить письмо с PDF</button></div><div id="sendFallback"><button class="btn" type="button" onclick="openEmail()">Открыть готовое письмо</button><button class="btn" type="button" onclick="downloadProposal()">Сохранить PDF</button><a class="btn" href="https://m.mustangtk.ru/" target="_blank" rel="noopener noreferrer">Открыть веб-почту Kerio</a></div><div id="sendStatus" role="status" aria-live="polite"></div><button class="btn" type="button" onclick="closeSendDialog()">Закрыть</button></form></div></div>`;
  document.body.append(...node.children);
  $('sendForm').addEventListener('submit',sendDirectProposal);
  for(const id of ['sendModal','shareModal'])$(id).addEventListener('click',e=>{if(e.target.id===id){if(id==='sendModal')closeSendDialog();else hideDialog(id)}});
}
async function shareProposal(){if(!validateProposal()||deliveryState.busy)return;deliveryState.busy=true;try{const blob=await makePdfBlob();deliveryState.sharedFile=new File([blob],proposalFilename(),{type:'application/pdf'});const supported=!!(navigator.share&&navigator.canShare?.({files:[deliveryState.sharedFile]}));$('nativeShareButton').hidden=!supported;$('shareHint').textContent=supported?'Выберите приложение и получателя в системном меню.':'Этот браузер не поддерживает передачу PDF в приложения. Сохраните файл и отправьте его из мессенджера.';showDialog('shareModal')}catch(e){toast('Не удалось подготовить PDF')}finally{deliveryState.busy=false}}
async function nativeShareProposal(){if(!deliveryState.sharedFile)return;try{await navigator.share({files:[deliveryState.sharedFile],title:'Коммерческое предложение · Агроинтеллект'});hideDialog('shareModal')}catch(e){if(e.name!=='AbortError')toast('Не удалось передать файл. Сохраните PDF и отправьте вручную.')}}
function endpointConfigured(){const endpoint=window.CALCULATOR_CONFIG?.sendEndpoint;try{const url=new URL(endpoint);return url.protocol==='https:'}catch(e){return false}}
let sendSnapshot=null;
function openSendDialog(){if(!validateProposal())return;if(!validEmail()){toast('Укажите корректный e-mail клиента');$('clientEmail').focus();return}const ready=endpointConfigured();$('kerioFields').hidden=!ready;$('sendFallback').hidden=ready;$('sendInfo').textContent=ready?'Письмо уйдёт с вашей рабочей почты. Коммерческое предложение будет вложено в PDF.':'Прямая отправка ещё не подключена: нужен защищённый сервер отправки и параметры SMTP Kerio. Пока можно открыть готовое письмо и прикрепить сохранённый PDF.';$('sendStatus').textContent='';sendSnapshot={client:client(),text:proposalText(),definition:proposalDocument(),filename:proposalFilename(),subject:productNames().join(' + ')+' — коммерческое предложение для '+client().name};$('sendReview').textContent='Получатель: '+sendSnapshot.client.email+' · '+fmt(totals().period);showDialog('sendModal')}
function closeSendDialog(){if(deliveryState.busy)return;$('senderPassword').value='';sendSnapshot=null;hideDialog('sendModal')}
function blobBase64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob)})}
async function sendDirectProposal(event){event.preventDefault();if(deliveryState.busy||!endpointConfigured()||!sendSnapshot||!$('sendForm').reportValidity())return;deliveryState.busy=true;$('sendButton').disabled=true;$('sendStatus').textContent='Формируем PDF и отправляем письмо…';const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),40000);try{const blob=await new Promise((resolve,reject)=>{try{pdfMake.createPdf(sendSnapshot.definition).getBlob(resolve)}catch(e){reject(e)}});const response=await fetch(CALCULATOR_CONFIG.sendEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({sender:$('senderEmail').value.trim(),password:$('senderPassword').value,to:sendSnapshot.client.email,subject:sendSnapshot.subject,text:'Добрый день!\n\n'+sendSnapshot.text+(sendSnapshot.client.manager?'\n\nС уважением,\n'+sendSnapshot.client.manager:''),pdfBase64:await blobBase64(blob),filename:sendSnapshot.filename})});if(!response.ok){if(response.status===401)throw new Error('Kerio не принял логин или пароль');if(response.status===429)throw new Error('Слишком много попыток. Повторите позже.');throw new Error('Сервер не подтвердил отправку')}const result=await response.json();if(result.sent!==true)throw new Error('Сервер не подтвердил отправку');$('sendStatus').textContent='Kerio принял письмо с PDF к отправке.';}catch(e){$('sendStatus').textContent=e.name==='AbortError'?'Время ожидания истекло. Проверьте отправку в почте перед повтором.':e.message;}finally{clearTimeout(timeout);$('senderPassword').value='';$('sendButton').disabled=false;deliveryState.busy=false}}
insertDeliveryDialogs();

