const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
module.exports={load};
function load(){const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const elements={};const cls=()=>({toggle(){},add(){},remove(){},contains(){return false}});for(const m of html.matchAll(/<[^>]+id="([^"]+)"[^>]*>/g)){const value=m[0].match(/value="([^"]*)"/)?.[1]||'';elements[m[1]]={value,textContent:'',innerHTML:'',classList:cls(),querySelector(){return {textContent:''}},setAttribute(){},checkValidity(){return true},focus(){}}}const shell={inert:false};const context=vm.createContext({Intl,Math,Date,Number,Map,String,console,setTimeout(){},clearTimeout(){},document:{getElementById(id){return elements[id]},querySelectorAll(){return []},querySelector(s){return s==='.shell'?shell:null},addEventListener(){},body:{style:{}}},window:{scrollTo(){}},navigator:{},URL});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app.js'),'utf8'),context);return {context,elements,run:code=>vm.runInContext(code,context)}}
test('Исходные тарифы: годовая и месячная оплата всех продуктов',()=>{const x=load();x.run("products={online:true,musoft:true,milk:true};farms[0].herd=850");x.elements.aiUsers.value='2';let t=x.run('totals()');assert.equal(t.online,20000);assert.equal(t.musoft,20000);assert.equal(t.milk,5000);assert.equal(t.ai,6000);assert.equal(t.net,51000);assert.equal(t.period,612000);x.run("paymentMode='monthly'");t=x.run('totals()');assert.equal(t.net,62450);assert.equal(t.period,62450)});
test('Все границы категорий поголовья',()=>{const x=load();for(const [herd,tier] of [[0,-1],[1,0],[100,0],[101,1],[500,1],[501,2],[1000,2],[1001,3],[1500,3],[1501,4],[2000,4],[2001,5]])assert.equal(x.run(`tierIndex(${herd})`),tier)});
test('Скидка, дополнительные системы, две площадки и ИИ',()=>{const x=load();x.run("products.online=true;farms=[newFarm('Первая'),newFarm('Вторая')];farms[0].extras=['1С'];farms[1].milking=false;farms[1].feeding=false");x.elements.aiUsers.value='3';x.elements.managerDiscount.value='10';const t=x.run('totals()');assert.equal(t.online,37500);assert.equal(t.gross,46500);assert.equal(t.discount,4650);assert.equal(t.net,41850);assert.equal(t.period,502200)});
test('Годовая скидка не может дать отрицательную стоимость',()=>{const x=load();x.run("products.musoft=true;farms[0].herd=100");x.elements.sStandaloneAnnual.value='150';assert.equal(x.run('totals().net'),0)});
test('Расчёт сохраняет копейки и согласует платёж за год',()=>{const x=load();x.run("products.online=true;farms[0].milking=false;farms[0].feeding=false");x.elements.sBase.value='100.01';x.elements.managerDiscount.value='17';const t=x.run('totals()');assert.equal(t.discount,17);assert.equal(t.net,83.01);assert.equal(t.period,996.12);assert.match(x.run('fmt(83.01)'),/83,01/)});
test('Нельзя выпустить КП без продукта, клиента или поголовья',()=>{const x=load();assert.equal(x.run('validateProposal()'),false);x.run('products.musoft=true');x.elements.clientName.value='Тестовый клиент';assert.equal(x.run('validateProposal()'),false);x.run('farms[0].herd=100');assert.equal(x.run('validateProposal()'),true);x.elements.clientName.value='';assert.equal(x.run('validateProposal()'),false)});
test('HTML инъекции экранируются и не попадают в разметку',()=>{const x=load();assert.equal(x.run(`esc('<img src=x onerror=alert(1)>')`),'&lt;img src=x onerror=alert(1)&gt;')});
test('Текст КП содержит состав площадок, поголовье и контакт',()=>{const x=load();x.run("products={online:true,musoft:true,milk:false};farms[0].herd=500;farms[0].extras=['1С']");x.elements.clientName.value='Тест';x.elements.contactName.value='Контакт';const text=x.run('proposalText()');assert.match(text,/поголовье 500/);assert.match(text,/1С/);assert.match(text,/Контакт/);assert.match(text,/Платёж за 12 месяцев/)});
test('Почтовый адрес не может добавить получателя и параметры URI',()=>{const x=load();x.elements.clientEmail.value='client@example.org?bcc=evil@example.org';assert.equal(x.run('validEmail()'),false);x.elements.clientEmail.value='client@example.org';assert.equal(x.run('validEmail()'),true);x.elements.clientName.value='Тест & проверка';assert.match(x.run('emailDraft()'),/^mailto:client%40example.org\?subject=/)});
test('Сброс возвращает продукты, площадки, пользователей и скидку',()=>{const x=load();x.run("products.online=true;farms.push(newFarm('Вторая'));paymentMode='monthly'");x.elements.aiUsers.value='5';x.elements.managerDiscount.value='25';x.run('resetAll()');assert.equal(x.run('productNames().length'),0);assert.equal(x.run('farms.length'),1);assert.equal(x.run('paymentMode'),'annual');assert.equal(Number(x.elements.managerDiscount.value),0);assert.equal(x.run('totals().net'),0)});

