const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
module.exports={load};
function load(){const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const elements={};const cls=()=>({toggle(){},add(){},remove(){},contains(){return false}});for(const m of html.matchAll(/<[^>]+id="([^"]+)"[^>]*>/g)){const value=m[0].match(/value="([^"]*)"/)?.[1]||'';elements[m[1]]={value,textContent:'',innerHTML:'',classList:cls(),querySelector(){return {textContent:''}},setAttribute(){},checkValidity(){return true},focus(){}}}const shell={inert:false};const context=vm.createContext({Intl,Math,Date,Number,Map,String,console,setTimeout(){},clearTimeout(){},document:{getElementById(id){return elements[id]},querySelectorAll(){return []},querySelector(s){return s==='.shell'?shell:null},addEventListener(){},body:{style:{}}},window:{scrollTo(){}},navigator:{},URL});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app.js'),'utf8'),context);return {context,elements,run:code=>vm.runInContext(code,context)}}
test('Новые тарифы при 850 головах; Онлайн-ферма и ИИ без изменений',()=>{const x=load();x.run("products={online:true,musoft:true,milk:true};farms[0].herd=850");x.elements.aiUsers.value='2';let t=x.run('totals()');assert.equal(t.online,20000);assert.equal(t.musoft,22900);assert.equal(t.milk,5575);assert.equal(t.ai,6000);assert.equal(t.net,54475);assert.equal(t.period,653700);x.run("paymentMode='monthly'");t=x.run('totals()');assert.equal(t.online,24000);assert.equal(t.ai,7200);assert.equal(t.net,66794);assert.equal(t.period,66794)});
test('Все границы категорий поголовья',()=>{const x=load();for(const [herd,tier] of [[0,-1],[1,0],[100,0],[101,1],[500,1],[501,2],[1000,2],[1001,3],[1500,3],[1501,4],[2000,4],[2001,5]])assert.equal(x.run(`tierIndex(${herd})`),tier)});
test('Скидка, дополнительные системы, две площадки и ИИ',()=>{const x=load();x.run("products.online=true;farms=[newFarm('Первая'),newFarm('Вторая')];farms[0].extras=['1С'];farms[1].milking=false;farms[1].feeding=false");x.elements.aiUsers.value='3';x.elements.managerDiscount.value='10';const t=x.run('totals()');assert.equal(t.online,37500);assert.equal(t.gross,46500);assert.equal(t.discount,4650);assert.equal(t.net,41850);assert.equal(t.period,502200)});
test('Базовая цена годовой оплаты не получает повторную скидку',()=>{const x=load();x.run("products.musoft=true;farms[0].herd=100");assert.equal(x.run('totals().net'),6250);assert.equal(x.run('totals().period'),75000);x.elements.sStandaloneMarkup.value='0';x.run("paymentMode='monthly'");assert.equal(x.run('totals().net'),6250)});
test('450 голов по таблице, дробная ставка сохраняет точность',()=>{const x=load();x.run("products={online:false,musoft:true,milk:true};farms[0].herd=450");const t=x.run('totals()');assert.equal(t.musoft,16532);assert.equal(t.milk,3750);assert.equal(t.period,243384);assert.match(x.run("standaloneFormula(farms[0],'musoft')"),/29,375/)});
test('Минимум 50, все переходы категорий и открытый диапазон >2000',()=>{const x=load();x.run("products={online:false,musoft:true,milk:true}");for(const [herd,mu,mi] of [[0,0,0],[1,3125,1000],[49,3125,1000],[50,3125,1000],[51,3188,1020],[100,6250,2000],[101,6280,2005],[500,18000,4000],[501,18014,4005],[1000,25000,6250],[1001,25014,6254],[1500,32000,8000],[1501,32016,8004],[2000,40000,10000],[2001,40012,10003],[3000,52000,13000]]){x.run(`farms[0].herd=${herd}`);const t=x.run('totals()');assert.equal(t.musoft,mu,'Мусофт: '+herd);assert.equal(t.milk,mi,'Учёт молока: '+herd)}});
test('Каждая площадка получает свой тариф, скидка применяется к общей цене',()=>{const x=load();x.run("products={online:false,musoft:true,milk:true};farms=[newFarm('А'),newFarm('Б')];farms[0].herd=450;farms[1].herd=50");x.elements.managerDiscount.value='10';const t=x.run('totals()');assert.equal(t.gross,24407);assert.equal(t.discount,2440);assert.equal(t.net,21967);assert.equal(t.period,263604)});
test('Min, фиксированная цена и цена за голову редактируются независимо',()=>{const x=load();x.run("products={online:true,musoft:true,milk:true};farms[0].herd=450");x.elements.tierMin1.value='120';x.elements.mu1.value='7000';x.elements.muRate1.value='30';const t=x.run('totals()');assert.equal(t.musoft,16900);assert.equal(t.milk,3650);assert.equal(t.online,20000)});
test('Стоимость после скидки округляется вверх, год = целый месяц × 12',()=>{const x=load();x.run("products.online=true;farms[0].milking=false;farms[0].feeding=false");x.elements.sBase.value='100.01';x.elements.managerDiscount.value='17';const t=x.run('totals()');assert.equal(t.gross,101);assert.equal(t.net,84);assert.equal(t.discount,17);assert.equal(t.period,1008);assert.equal(t.gross-t.discount,t.net);assert.equal(x.run('fmt(83.01)'),'84 ₽')});
test('Целые суммы не растут от погрешности floating point, дробные растут вверх',()=>{const x=load();for(const [input,expected] of [['0',0],['100',100],['100.001',101],['100.5',101],['210*1.1',231],['16531.25',16532]])assert.equal(x.run(`money(${input})`),expected)});
test('HTML инъекции экранируются и не попадают в разметку',()=>{const x=load();assert.equal(x.run(`esc('<img src=x onerror=alert(1)>')`),'&lt;img src=x onerror=alert(1)&gt;')});
test('Сброс возвращает продукты, площадки, пользователей и скидку',()=>{const x=load();x.run("products.online=true;farms.push(newFarm('Вторая'));paymentMode='monthly'");x.elements.aiUsers.value='5';x.elements.managerDiscount.value='25';x.run('resetAll()');assert.equal(x.run('productNames().length'),0);assert.equal(x.run('farms.length'),1);assert.equal(x.run('paymentMode'),'annual');assert.equal(Number(x.elements.managerDiscount.value),0);assert.equal(x.run('totals().net'),0)});

