import {test} from 'node:test';import assert from 'node:assert/strict';import {validateMail,createSender} from '../server/index.mjs';
const payload={sender:'manager@example.org',to:'client@example.org',password:'test-only-password',subject:'КП',text:'Тест',pdfBase64:Buffer.from('%PDF-1.3\ntest').toString('base64'),filename:'КП.pdf'};
const config={origin:'https://example.org',smtpHost:'mail.example.org',smtpPort:587,domains:['example.org']};
function request(server,{origin=config.origin,method='POST',body=payload,contentType='application/json'}={}){return new Promise(resolve=>{const headers={origin,'content-type':contentType};const req={headers,method,url:'/api/send-proposal',socket:{remoteAddress:'test-ip'},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(body))}};const res={headers:{},setHeader(k,v){this.headers[k]=v},writeHead(status){this.status=status},end(text){resolve({status:this.status,body:text?JSON.parse(text):null,headers:this.headers})}};server.emit('request',req,res)})}
test('Проверяет SMTP-получателя, домен менеджера и PDF',()=>{assert.equal(validateMail(payload,['example.org']).sender,payload.sender);assert.throws(()=>validateMail({...payload,sender:'someone@evil.org'},['example.org']));assert.throws(()=>validateMail({...payload,to:'a@example.org,b@example.org'},['example.org']));assert.throws(()=>validateMail({...payload,pdfBase64:Buffer.from('not a pdf').toString('base64')},['example.org']));assert.throws(()=>validateMail({...payload,subject:'hello\r\nBcc: evil'},['example.org']))});
test('Нельзя запустить сервер без HTTPS origin и подтверждённой конфигурации',()=>{assert.throws(()=>createSender({...config,origin:'http://example.org'}));assert.throws(()=>createSender({...config,domains:[]}));assert.throws(()=>createSender({...config,smtpPort:25}))});
test('Чужой origin не получает доступ к отправке',async()=>{let used=false;const server=createSender({...config,transportFactory(){used=true}});const result=await request(server,{origin:'https://evil.org'});assert.equal(result.status,403);assert.equal(used,false);server.close()});
test('SMTP отправляет письмо от менеджера с PDF и включает TLS',async()=>{let options,mail,closed=false;const server=createSender({...config,transportFactory(o){options=o;return {async sendMail(m){mail=m;return {accepted:[payload.to]}},close(){closed=true}}}});const result=await request(server);assert.equal(result.status,200);assert.equal(result.body.sent,true);assert.equal(options.requireTLS,true);assert.equal(options.tls.rejectUnauthorized,true);assert.equal(mail.from,payload.sender);assert.equal(mail.attachments[0].contentType,'application/pdf');assert.equal(mail.disableUrlAccess,true);assert.equal(closed,true);server.close()});
test('Неверный пароль и ошибка SMTP не возвращают ложный успех',async()=>{for(const code of ['EAUTH','ECONNECTION']){const server=createSender({...config,transportFactory(){return {async sendMail(){throw Object.assign(new Error('secret details'),{code})},close(){}}}});const result=await request(server);assert.equal(result.status,code==='EAUTH'?401:502);assert.equal(result.body.sent,false);assert.ok(!JSON.stringify(result).includes('secret details'));server.close()}});
test('Лимит запросов защищает повторные попытки авторизации',async()=>{const server=createSender({...config,transportFactory(){return {async sendMail(){return {accepted:[payload.to]}},close(){}}}});for(let i=0;i<20;i++)assert.equal((await request(server)).status,200);assert.equal((await request(server)).status,429);server.close()});
